steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud functions deploy function_cicd \
          --region=europe-west2 \
          --source=. \
          --trigger-http \
          --runtime=python39 \
          --allow-unauthenticated
options:
  logging: CLOUD_LOGGING_ONLY
  
